<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Shop by category</name>
   <tag></tag>
   <elementGuidId>5206cf27-7699-40b4-9475-2a0c9e6ee7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-shop-a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gh-shop-a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>707fce96-4d72-4b86-9b29-53a4199388ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-shop-a</value>
      <webElementGuid>619e9cb7-fe7f-4550-b001-ea18850e825a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a1288e7-f382-49b2-bcc1-b3aa0da08a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gh-control</value>
      <webElementGuid>56223762-11b4-4346-b7af-6909318dad27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>gh-sbc-o</value>
      <webElementGuid>6db650b6-00c9-49dc-9146-7dc146d0ba2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Shop by category</value>
      <webElementGuid>88317ba1-5008-46fd-8816-1859470f86ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-shop-a&quot;)</value>
      <webElementGuid>bf97bae0-02cf-4265-9aca-556fa708a021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gh-shop-a']</value>
      <webElementGuid>ce5b7852-7cd3-4dae-977a-9062af5c5041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gh-shop']/button</value>
      <webElementGuid>c7751001-2772-4d3f-a2d0-8a2cfd070b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[1]</value>
      <webElementGuid>bde1b6aa-4881-4d04-82a6-9540bddf1df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by category'])[2]/preceding::button[1]</value>
      <webElementGuid>935bd225-472b-40ea-9965-723493cf6282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collectibles &amp; art'])[1]/preceding::button[1]</value>
      <webElementGuid>feedcf72-5ba4-401b-8362-b09154097f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shop by category']/parent::*</value>
      <webElementGuid>5273bbac-35b0-46a4-b6ab-af33b52504c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7a163bab-758a-46be-962a-0652dd4a3cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gh-shop-a' and (text() = ' Shop by category' or . = ' Shop by category')]</value>
      <webElementGuid>1965c845-caa4-4ffc-8c16-3801fd427b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
