<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_macbook_gh-btn</name>
   <tag></tag>
   <elementGuidId>4872fd09-e571-4799-82cc-cf5b1ab6e83e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gh-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e32a7003-c52a-44e2-88be-d57532cfbaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d997affb-2a16-44be-afeb-7957d6a4673f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-prim gh-spr</value>
      <webElementGuid>f65843ff-5fc5-4bd4-ac83-2fe19a193f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-btn</value>
      <webElementGuid>c6ec4257-b982-4ad2-a310-ca98b6eb7fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3abf6c0b-4569-4926-b67e-023470f27ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>gh-f</value>
      <webElementGuid>48c8f541-34ca-4f5d-aabe-d3961e9bfbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-btn&quot;)</value>
      <webElementGuid>bb8ffda7-5b1e-4250-a7c8-cf266abad111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gh-btn']</value>
      <webElementGuid>03d81a1c-0e2e-49ea-a390-3d4818e4c4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gh']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>09a2f885-aedd-4aca-88e6-bdc70aa37b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>69e56558-fd2b-4f7b-b2be-4acfda4c8982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'gh-btn' and @form = 'gh-f']</value>
      <webElementGuid>f034c3cf-b428-431b-bf28-a019050f04f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
