<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>4c87cc91-aa89-4e34-a5e4-b7e93ddcb3c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.x-overlay-footer__apply-btn.btn.btn--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[30]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d17751a9-759f-49ca-a896-e6fe1fe94b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;LST&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;actionKind&quot;:&quot;SUBMIT&quot;,&quot;actionKinds&quot;:[&quot;SUBMIT&quot;],&quot;operationId&quot;:&quot;2489524&quot;,&quot;flushImmediately&quot;:false,&quot;eventProperty&quot;:{&quot;parentrq&quot;:&quot;51643b911920a5724c4f48f9fff551f8&quot;,&quot;pageci&quot;:&quot;6aa376d4-5084-4c7e-b8a7-cf1e8ff57fae&quot;,&quot;moduledtl&quot;:&quot;mi%3A4118%7Ciid%3A1%7Cli%3A8171%7Cluid%3A314%7C%7C&quot;},&quot;aspectsBefore&quot;:{&quot;_fsrp&quot;:&quot;0&quot;,&quot;rt&quot;:&quot;nc&quot;,&quot;_sacat&quot;:&quot;9355&quot;,&quot;no_encode_refine_params&quot;:&quot;1&quot;}}</value>
      <webElementGuid>0ad28997-208a-49b9-8d61-981d3af636e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-overlay-footer__apply-btn btn btn--primary</value>
      <webElementGuid>f7a5342b-0536-411b-8e04-de9553c7c060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5430b322-d6b8-466b-abdd-69927458c6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>fc5b09cc-ba30-48ae-92da-2b660ad230c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>3432a556-903d-4cc1-906d-07d944fca0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;x-overlay__form&quot;)/div[@class=&quot;x-overlay-footer&quot;]/div[@class=&quot;x-overlay-footer__apply&quot;]/button[@class=&quot;x-overlay-footer__apply-btn btn btn--primary&quot;]</value>
      <webElementGuid>06360c19-edac-4893-858a-2a05fa96b7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[30]</value>
      <webElementGuid>45ca2103-5f46-4961-a2ec-be4316e2105e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='x-overlay__form']/div[3]/div[2]/button</value>
      <webElementGuid>d991b44c-41bf-42d3-8a37-894c44aa332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[2]/following::button[2]</value>
      <webElementGuid>b52cf450-d4ef-4270-ad9e-2869499298ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>0274bec3-87c4-40ee-a696-58f58111a4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b10065f1-c76c-4303-85ce-d6aa138ceee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>357081c1-b900-41d5-b12b-49c7b43f9930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
