<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Condition</name>
   <tag></tag>
   <elementGuidId>449aed01-4ce9-48b3-a7c6-afc09108dc1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-mainPanel-condition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c3-mainPanel-condition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f273c6a5-5bc0-4574-8bee-38e7f1df49a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6901bed1-e4d9-4462-b5fd-a626102128d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-overlay-aspect </value>
      <webElementGuid>5738760a-6d9a-480c-8e65-145428c71bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aspecttitle</name>
      <type>Main</type>
      <value>LH_ItemCondition</value>
      <webElementGuid>bc62f02a-dfa6-4773-94da-7abec8102b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4897bb37-24fd-4151-b815-2b8b56367d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>refineOverlay-subPanel</value>
      <webElementGuid>89072aa0-c25f-4e1a-abee-9ac9063e707d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3-mainPanel-condition</value>
      <webElementGuid>52b532c8-973b-4e94-8f2b-4eb9876d7453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Condition</value>
      <webElementGuid>26674571-36d2-4e16-a70e-efdc40a0c614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-mainPanel-condition&quot;)</value>
      <webElementGuid>ca7c1302-2698-4347-b111-11fbb5dcbb2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='c3-mainPanel-condition']</value>
      <webElementGuid>32a7ffbe-bc60-4f4f-8f78-a3d686edd7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-mainPanel']/div[7]</value>
      <webElementGuid>11fb4d34-0608-4831-95ca-67b40c0274e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]</value>
      <webElementGuid>298e15d1-2a49-4566-aeb4-0ea4ccb157d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'c3-mainPanel-condition' and (text() = 'Condition' or . = 'Condition')]</value>
      <webElementGuid>fa4ad1b0-b1ac-4555-a535-3f9c21579dd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
