<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDR_x-textrange__input x-textrange__i_f04732</name>
   <tag></tag>
   <elementGuidId>9c89a3c5-04aa-454f-b325-3088ad37dd3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.x-textrange__input.x-textrange__input--from</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>735afc73-fc3c-4f3d-8ed7-566a72fcb87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>a9b91e2b-026d-42a3-a674-097aaa6f1d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6e6fd6e-8a75-4082-8669-f01c354519dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>aee97502-fc47-4dad-8942-cf3262aa8b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>86ddd945-4bb9-431b-b180-fc4323e66620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Minimum Value, US Dollar</value>
      <webElementGuid>ed4b2be2-d65b-46b9-a2ac-9f9147f20ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-textrange__input x-textrange__input--from</value>
      <webElementGuid>7876cd59-4e68-4607-9df3-f4eeec579995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c7d5d40-e0c9-4629-aa98-b94bb56e4e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d442ef0-e5f4-49f7-8398-bfc613b1cfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-subPanel-_x-price-textrange&quot;)/div[@class=&quot;x-textrange&quot;]/div[1]/div[@class=&quot;x-textrange__block&quot;]/input[@class=&quot;x-textrange__input x-textrange__input--from&quot;]</value>
      <webElementGuid>2ca7b76c-44d1-4db1-bfa5-692041b0053b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>69b0e8e2-a821-4a61-84e8-1edf55ee5de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-subPanel-_x-price-textrange']/div/div/div/input</value>
      <webElementGuid>a1e95c5a-84a8-46d5-99a7-5926a5c81c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>2254f2ca-be83-4c56-8725-0325dffd800e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>2f84b016-76ef-468f-9694-2528fdb186f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
