<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Europe_location</name>
   <tag></tag>
   <elementGuidId>ff5dc439-79c7-4ae0-af17-570394fc6cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-subPanel-location_Asia > span.field > span.radio.field__control.rbx.x-refine__single-select-radio > input[name=&quot;location&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='location'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>302ea5d4-9e74-4d57-a5e0-6d967e9a102b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3003af7e-bbe5-4ddb-8bec-67cab1c37c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2977be8e-e5ba-4f1f-82e9-9e85d6287d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asia</value>
      <webElementGuid>eef80cc8-9c6d-4dd6-991b-4deaff723e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Asia</value>
      <webElementGuid>71206920-707c-444e-9294-274ffaee5046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>f8707274-742a-4d37-bc12-6feabc13d8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0856366c-d495-492a-9c46-079e9e51ac4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a5583a63-41cb-4e0a-995b-7d36d5f26053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio__control</value>
      <webElementGuid>5328de94-081e-4727-bca2-2ed5031f0de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-subPanel-location_Asia&quot;)/span[@class=&quot;field&quot;]/span[@class=&quot;radio field__control rbx x-refine__single-select-radio&quot;]/input[@class=&quot;radio__control&quot;]</value>
      <webElementGuid>0c7972cc-dc1e-4324-8a96-8380f2c604c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='location'])[5]</value>
      <webElementGuid>7366f957-bb58-48e5-84ed-d00296d0857a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-subPanel-location_Asia']/span/span/input</value>
      <webElementGuid>f8e75267-2254-4b2a-8c50-182551167d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/span/input</value>
      <webElementGuid>151fa185-14a7-4037-85e5-62b17e9a6138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'location' and @type = 'radio']</value>
      <webElementGuid>668565b6-58f8-4e28-bc64-37df19e3a838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
