<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Condition_c3-subPanel-LH_ItemConditio_4a9678</name>
   <tag></tag>
   <elementGuidId>073d3db7-b31c-41a8-8687-d299250f428f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-subPanel-LH_ItemCondition_New_cbx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c3-subPanel-LH_ItemCondition_New_cbx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>412ef0eb-daa2-4633-9437-174adbe41f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90b2d20b-98c6-46c5-8fd7-10ed6fe765c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0b8d034-8824-4be4-80a8-06ff1284d6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4485260e-a39c-4009-9c3a-6ef6c270e20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3-subPanel-LH_ItemCondition_New_cbx</value>
      <webElementGuid>aeeab737-a060-415f-87c4-1a289956330b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>792699d9-a7de-40cd-9986-8b84b857e87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox__control</value>
      <webElementGuid>6390ce67-4a98-45e5-8169-7b5f25918cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c3ce7915-ffc3-4aaa-b215-85bfdd570f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-subPanel-LH_ItemCondition_New_cbx&quot;)</value>
      <webElementGuid>2f23abdf-ab6b-4348-941d-c8f6d555f6a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c3-subPanel-LH_ItemCondition_New_cbx']</value>
      <webElementGuid>6b875019-b9b0-4d44-9c00-d0a6577c4e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-subPanel-LH_ItemCondition_New']/span/span/input</value>
      <webElementGuid>8a4e24fa-dbc5-447c-bc71-5ee9209bd473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>3998d358-3e94-4fad-ba85-0de3acfcb6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c3-subPanel-LH_ItemCondition_New_cbx' and @type = 'checkbox']</value>
      <webElementGuid>6f037564-bbe3-4598-b9a5-131b342e8b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
