<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your search keyword_gh-btn</name>
   <tag></tag>
   <elementGuidId>c765a828-f1ed-41b3-a2e8-2a374dcbfc20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gh-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gh-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0adf19d9-6718-45f7-bf10-8f455b612f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5aa17a0f-28b8-47ca-81ed-6080d0c1f0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-prim gh-spr</value>
      <webElementGuid>eeef3450-ef95-4b93-a212-29640360fb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gh-btn</value>
      <webElementGuid>a3fa10cc-9066-4dd0-baf7-151860312b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3a03491e-cb17-4703-9698-1e9abd961187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>gh-f</value>
      <webElementGuid>fb066d29-f30b-49a1-945c-327adb190ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gh-btn&quot;)</value>
      <webElementGuid>139d155d-e54c-4393-b69c-d0b91726f0c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gh-btn']</value>
      <webElementGuid>5b56973b-3ba0-41e1-a894-b793d7fc0bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='gh']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>cfc746d4-5fcb-425a-873f-09d870fe2ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>f08110c2-a438-4a83-a5fa-ec0e956b2400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'gh-btn' and @form = 'gh-f']</value>
      <webElementGuid>7ce4b2a7-2daa-4e89-9793-8ae5b6c2ab75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
